### ISSUE TITLE
Do you support ESP32 devices?

### ISSUE THREAD

**Issue by Ks89** [Seeed-Studio/Grove_Air_quality_Sensor#10]
Is it possibile to use this library on a ESP32 S2 device with [arduino-esp32](https://github.com/espressif/arduino-esp32)

**Comment by Ks89** [comment]
After some tests I can confirm that it's working also on ESP32, however you have to download this repo manually, because the latest stable release (1.0.0) available in ArduinoIDE library manager is not working, because too old.

Could you create a new version and release it in Arduino IDE library manager?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

I've tested it and it's currently possible to download the library with Arduino version 2.3.2.
The management address of the development board I am using is `https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json`

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
