### ISSUE TITLE
[Feature] Any chance of getting Xiao nRF52 support?

### ISSUE THREAD

**Issue by flexmox** [Seeed-Studio/Grove_Air_quality_Sensor#11]
I hooked up my brand new Xiao BLE Sense with the Grove air quality sensor only to find out the library only supports specific types of devices because of the way it uses interrupts.  Is it possible to make the Grove Air Quality Sensor compatible with Xiao BLE Sense boards (nRF52)?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still need this feature now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
