### ISSUE TITLE
Example on wiki broken

### ISSUE THREAD

**Issue by doriath** [Seeed-Studio/Grove_Air_quality_Sensor#2]
Hi,

In commit 1df9089276e7d179ed2fd43f0dc41beea67abdfe, the interface to AirQuality::init(int pin) changed from receiving one argument to receiving two arguments. It breaks the example on following wiki:

http://www.seeedstudio.com/wiki/Grove_-_Air_Quality_Sensor

That is calling:

airqualitysensor.init(14);

**Comment by KillingJacky** [comment]
closed this, feel free to reopen for further questions.

**Comment by KillingJacky** [comment]
closed this, feel free to reopen for further questions.
