### ISSUE TITLE
vol_standard calculated incorrectly in void AirQuality::avgVoltage() due to int overflow

### ISSUE THREAD

**Issue by Baglan** [Seeed-Studio/Grove_Air_quality_Sensor#5]
Hi!

First of all, thank you for creating the Groves - they are amazingly easy to use!

I've recently used AirQuality Sensor Grove in my project and noticed that, after 5 minutes, the value returned by int AirQuality::slope(void) would always be 1 (High pollution), although before that, value was 3 (Air fresh) with sensor reading of ~250.

Turns out, on my system, the size of the int was 16 bits and 'temp' populated with 150 samples was overflowing, resulting in a negative value; this means that vol_standard would also become negative and this expression would always evaluate to true:

first_vol - vol_standard > 150

Possible fixes:
a. Use a larger data type for 'temp' (say, long);
b. Use a low pass filter instead of averaging over 150 samples (which also has an advantage of a constantly updated rather than "jumping" average with a similar computational load).

Please let me know if you would like me to implement the changes and, if so, which solution would be more appropriate.

Cheers,
–Baglan

**Comment by KillingJacky** [comment]
Hi @Baglan so much thanks for your circumspection and your investigation. yes, it's an obvious mistake 😰  
I think I prefer the solution (a), 1st it will let the slope method work with proof (note 1), 2nd solution (b) may have a short that the vol_standard will follow the curve of the realtime measurement, so the threshold of the value jump for triggering the alarm must be reevaluated, and I think that will take a lot of efforts.
note 1 - though the trigger will possibly have (maximum) 3 minutes late, apparently it will miss an emergency alarm, but we have the most emergency case covered with the "High pollution! Force signal active." if branch 😄 
Anyway I performed the solution a firstly. And what you think about the choice.

**Comment by Baglan** [comment]
Thank you so much @KillingJacky!

I'll close the issue if you don't mind.

**Comment by KillingJacky** [comment]
Sure not.
