### ISSUE TITLE
Working with Arduino Leonardo

### ISSUE THREAD

**Issue by omarecd** [Seeed-Studio/Grove_Air_quality_Sensor#8]
Dear team.
Thanks for the great work with the sensor.

Question:
To test that everything worked fine, I started with the example provided on the library. When I compile for the board Arduino Uno it works, however when I compile for the Arduino **Leonardo**, it doesn't work (I should use Leonardo for my project).
- Does this library works with an Arduino Leonardo ? (I need to use Arduino Leonardo)
Kind regards.
Omar C.

Ps.
I also trying modifying the .cpp file, replacing the current values (like TCCR2A) by the proposed values (TCCR0A). Then, compilation was "ok", however the sensor is not behaving as expected. Any ideas? Thanks.

=================
Error msg starts like that:
=================

Arduino: 1.8.10 (Linux), Board: "Arduino Leonardo"

In file included from /home/o/Downloads/arduino-1.8.10/hardware/arduino/avr/cores/arduino/Arduino.h:30:0,
                 from /home/o/Arduino/libraries/Grove_-_Air_quality_sensor/AirQuality.h:23,
                 from /home/o/Arduino/libraries/Grove_-_Air_quality_sensor/examples/AirQuality_Sensor/AirQuality_Sensor.ino:6:
/home/o/Arduino/libraries/Grove_-_Air_quality_sensor/examples/AirQuality_Sensor/AirQuality_Sensor.ino: In function 'void TIMER2_OVF_vect()':
/home/o/Arduino/libraries/Grove_-_Air_quality_sensor/examples/AirQuality_Sensor/AirQuality_Sensor.ino:30:5: warning: 'TIMER2_OVF_vect' appears to be a misspelled 'signal' handler, missing '__vector' prefix [-Wmisspelled-isr]
 ISR(TIMER2_OVF_vect)
     ^
/home/o/Arduino/libraries/Grove_-_Air_quality_sensor/AirQuality.cpp: In member function 'void AirQuality::init(int)':
/home/o/Arduino/libraries/Grove_-_Air_quality_sensor/AirQuality.cpp:80:5: **error: 'TCCR2A' was not declared in this scope
     TCCR2A=0;**//normal model
     ^~~~~~
/home/o/Arduino/libraries/Grove_-_Air_quality_sensor/AirQuality.cpp:80:5: note: **suggested alternative: 'TCCR0A'**
     TCCR2A=0;//normal model
     ^~~~~~
     TCCR0A

**Comment by Pillar1989** [comment]
I looked at the code and it wasn't on our GitHub. @omarecd

**Comment by albtrentadue** [comment]
@omarecd please check issue #9. I bet that now the library should work also for Leonardo

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
