### ISSUE TITLE
Not only AVR cards are supported

### ISSUE THREAD

**Issue by albtrentadue** [Seeed-Studio/Grove_Air_quality_Sensor#9]
When the current code is cloned and used within Arduino, it complains that only AVR mcu's are supported but actually it works also on SAMD cards - and I do not see a reason why it should not.
Maybe the setting `architectures=avr` in library.propoerties is outdated?
Current code in repo is much different from the one packed in the v1.0.1 release and it does not contain any AVR-only instruction.

BTW, the version currently installed through the Arduino IDE is v1.0.1 and this prevents the use of this library for other cards (e.g. SAMD ones like Arduino MKR) which would benefit from this sensor.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
